export type HttpMethod = "get" | "post" | "put" | "patch" | "delete";
export * from "./auth";
export * from "./statistic";
export * from "./transaction";
export * from "./collage";
export * from "./profile";
export * from "./upload";
export * from "./department";
export * from "./user";
export * from "./student";
export * from "./asign-teacher";
export * from "./admission";
export * from "./batch";
export * from "./subject";
export * from "./routine";
export * from "./event";
export * from "./exam";
export * from "./result";
